name: build/release dmx4esp

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  APP_NAME: dmx4esp

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package release
        run: ./scripts/package.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}
          path: ${{env.APP_NAME}}.zip
      - name: Create release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: ${{env.APP_NAME}}.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
